spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch?serverTimezone=Asia/Seoul
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 12081208

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always